export const colors = {
  'black': '#000', 
  'white': '#fff',
  'grey': '#acacac', 
  'pernia': '#e83647', 
  'pernia-lite': '#f9d9e4',
  'pernia-lighter': '#ffe7ef',
  'pernia-black': '#212121', 
  'pernia-dark-grey': '#757575', 
  'pernia-red': '#ef3e00', 
  'loyalty-bg': '#f4f1ff',
  'loyalty': '#6030ff',
  'grey-light': '#c2c2c2', 
  'placeholder': '#fafafa', 
  'placeholder-bg': '#dbdbdb', 
  'account-input': '#8c8c8c',
  'success': '#4BB543', 
  'slate': '#eef0f5', 
  'light-grey': '#f4f4f4', 
  'light-pink': '#ffdee1', 
  'special-red': '#9f0032', 
  'warning-red': '#ff3800', 
  'disabled': '#bbb',
  'label': '#333',
  'dark-grey': '#666',
}